# Site settings
email: lusiue@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Trophy
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: JangChulwoon
profile_img: https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/1958456_169082490150911_3396784208631173058_n.jpg?oh=be9d773db489dd01095cb02097b73eeb&oe=58FF7476
profile: hello?
social: 
  github: https://github.com/JangChulwoon

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
