# Site settings
email: lusiue@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Trophy
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: JangChulwoon
profile_img: 
profile: hello?
social: 
  github: https://github.com/JangChulwoon

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
